#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Standalone batch CLI generated by the Distance Scan plugin (Python zipapp).

This is the __main__.py of a self-contained .pyz archive. The input files
(data/input.prmtop, data/input.pdb) are embedded in the same archive and are
read via the 'zipfile' module, so no external files are needed.

Run with:
    python scan_script.pyz [options]

Scan parameters are baked in from the plugin GUI but can be overridden on the
command line. Use --params to print the effective settings, or --help for a
full list of options.
"""

import argparse
import os
import shutil
import sys
import tempfile
import zipfile

# Baked defaults (overridable from the command line). The @@MARKER@@ tokens
# are replaced by the plugin when this file is packed into the archive.
DEFAULT_GROUP1 = @@G1@@
DEFAULT_GROUP2 = @@G2@@
DEFAULT_START = @@START@@
DEFAULT_END = @@END@@
DEFAULT_WINDOWS = @@NWINDOWS@@
DEFAULT_FORCE_CONSTANT = @@FORCE@@
DEFAULT_TOLERANCE = @@TOL@@
DEFAULT_MAX_ITER = @@MAX_ITER@@
DEFAULT_IMPLICIT_SOLVENT = @@IMPLICIT@@

EMBEDDED_PRMTOP = 'data/input.prmtop'
EMBEDDED_PDB = 'data/input.pdb'


def read_embedded(name):
    """Read a file embedded in this zipapp archive."""
    archive_path = os.path.abspath(sys.argv[0])
    with zipfile.ZipFile(archive_path, 'r') as zf:
        return zf.read(name)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Distance-constrained minimization scan (self-contained).',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument('-o', '--output', default='scan_results.pdb',
                        help='output multi-model PDB path')
    parser.add_argument('-s', '--start', type=float, default=DEFAULT_START,
                        help='start distance (nm)')
    parser.add_argument('-e', '--end', type=float, default=DEFAULT_END,
                        help='end distance (nm)')
    parser.add_argument('-n', '--windows', type=int, default=DEFAULT_WINDOWS,
                        help='number of windows')
    parser.add_argument('-k', '--force-constant', type=float,
                        default=DEFAULT_FORCE_CONSTANT,
                        help='harmonic force constant (kJ/mol/nm^2)')
    parser.add_argument('--tolerance', type=float, default=DEFAULT_TOLERANCE,
                        help='minimization tolerance (kJ/mol)')
    parser.add_argument('--max-iter', type=int, default=DEFAULT_MAX_ITER,
                        help='max minimization iterations per window')
    parser.add_argument('--implicit', action='store_true',
                        default=bool(DEFAULT_IMPLICIT_SOLVENT),
                        help='use OBC2 implicit solvent (forces NoCutoff)')
    parser.add_argument('--platform', default=os.environ.get('OPENMM_PLATFORM', ''),
                        help='OpenMM platform name (default: auto-select)')
    parser.add_argument('--params', action='store_true',
                        help='print effective parameters and exit')
    return parser.parse_args()


def validate(args):
    if args.start >= args.end:
        raise SystemExit('error: --start must be less than --end')
    if args.windows < 2:
        raise SystemExit('error: --windows must be at least 2')
    if args.max_iter < 1:
        raise SystemExit('error: --max-iter must be at least 1')


def run_scan(args, prmtop_file, pdb_file):
    """Lazy OpenMM import keeps --help/--params usable without OpenMM."""
    import numpy as np
    import openmm as mm
    from openmm import unit
    from openmm.app import AmberPrmtopFile, PDBFile, Simulation

    prmtop = AmberPrmtopFile(prmtop_file)
    pdb = PDBFile(pdb_file)
    n_atoms = prmtop.topology.getNumAtoms()

    # Periodicity. Implicit solvent requires NoCutoff (OBC2 is incompatible
    # with periodic PME), so the box is ignored in that case.
    box_vectors = pdb.topology.getPeriodicBoxVectors()
    if args.implicit or box_vectors is None:
        nonbondedMethod = mm.app.NoCutoff
        nonbondedCutoff = None
    else:
        nonbondedMethod = mm.app.PME
        nonbondedCutoff = 1.0 * unit.nanometer

    system = prmtop.createSystem(
        nonbondedMethod=nonbondedMethod,
        nonbondedCutoff=nonbondedCutoff,
        constraints=mm.app.HBonds,
        rigidWater=False,
        implicitSolvent=mm.app.OBC2 if args.implicit else None,
    )

    # Centroid force between the two embedded groups
    centroid_force = mm.CustomCentroidBondForce(2, 'distance(g1, g2)')
    centroid_force.addGroup(DEFAULT_GROUP1)
    centroid_force.addGroup(DEFAULT_GROUP2)
    centroid_force.addBond([0, 1], [])

    # Bias (harmonic restraint)
    bias = mm.CustomCVForce('0.5 * k * (cv1 - target)^2')
    bias.addCollectiveVariable('cv1', centroid_force)
    bias.addGlobalParameter('k', args.force_constant * unit.kilojoule_per_mole / unit.nanometer ** 2)
    bias.addGlobalParameter('target', 0.0 * unit.nanometer)
    system.addForce(bias)

    integrator = mm.LangevinIntegrator(300 * unit.kelvin, 1.0 / unit.picosecond,
                                       0.002 * unit.picoseconds)
    if args.platform:
        simulation = Simulation(prmtop.topology, system, integrator,
                                mm.Platform.getPlatformByName(args.platform))
        print('Using platform: %s' % args.platform)
    else:
        simulation = Simulation(prmtop.topology, system, integrator)
    simulation.context.setPositions(pdb.positions)
    if box_vectors is not None:
        simulation.context.setPeriodicBoxVectors(*box_vectors)

    # Scan – write each model immediately to bound memory (streaming)
    targets = np.linspace(args.start, args.end, args.windows)
    with open(args.output, 'w') as f:
        for i, target in enumerate(targets):
            print('Window %d/%d: target = %.3f nm' % (i + 1, args.windows, target))
            simulation.context.setParameter('target', target * unit.nanometer)
            simulation.minimizeEnergy(tolerance=args.tolerance,
                                      maxIterations=args.max_iter)
            state = simulation.context.getState(getPositions=True)
            pos = state.getPositions(asNumpy=True).value_in_unit(unit.nanometer)
            if len(pos) > n_atoms:
                print('Warning: Context has %d particles, topology has %d atoms. Truncating.'
                      % (len(pos), n_atoms))
                pos = pos[:n_atoms]
            elif len(pos) < n_atoms:
                raise RuntimeError('Context has fewer particles (%d) than topology (%d).'
                                   % (len(pos), n_atoms))
            f.write('MODEL     %d\n' % (i + 1))
            PDBFile.writeModel(prmtop.topology, pos * unit.nanometer, f, keepIds=True)
            f.write('ENDMDL\n')

    print('Done! Results saved to %s' % args.output)


def main():
    args = parse_args()
    if args.params:
        print('Group1: %d atoms' % len(DEFAULT_GROUP1))
        print('Group2: %d atoms' % len(DEFAULT_GROUP2))
        print('start = %.3f nm' % args.start)
        print('end   = %.3f nm' % args.end)
        print('windows = %d' % args.windows)
        print('force constant = %g kJ/mol/nm^2' % args.force_constant)
        print('tolerance = %g kJ/mol' % args.tolerance)
        print('max iterations = %d' % args.max_iter)
        print('implicit solvent = %s' % args.implicit)
        print('platform = %s' % (args.platform or 'auto'))
        print('output = %s' % args.output)
        return 0

    validate(args)

    tmpdir = tempfile.mkdtemp(prefix='scan_batch_')
    try:
        for member, suffix in [(EMBEDDED_PRMTOP, '.prmtop'),
                               (EMBEDDED_PDB, '.pdb')]:
            data = read_embedded(member)
            path = os.path.join(tmpdir, 'input' + suffix)
            with open(path, 'wb') as f:
                f.write(data)
        run_scan(args, os.path.join(tmpdir, 'input.prmtop'),
                 os.path.join(tmpdir, 'input.pdb'))
        return 0
    finally:
        shutil.rmtree(tmpdir, ignore_errors=True)


if __name__ == '__main__':
    sys.exit(main())